[package]
name = "penrose"
version = "0.1.0"
authors = ["mamimi_cooly <mamimi_cooly@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.1.8"
