add_newline = false

format = """\
    [|>](bold #b18ef9) \
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $character
"""

[directory]
style = "bold cyan"

[character]
success_symbol = '[->](bold green)'
error_symbol = '[->](bold red)'
