add_newline = false

format = """\
    [|> ](bold #b18ef9)\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $character
"""

[directory]
style = "bold cyan"

[git_branch]
truncation_length = 35

[character]
success_symbol = "[->](bold green)"
error_symbol = "[->](bold red)"
vimcmd_symbol = "[<-](bold green)"
