- name: Delete .profile from home folder
  file:
    path: "/home/{{ user }}/.profile"
    state: absent

- name: Delete .zprofile from home folder
  file:
    path: "/home/{{ user }}/.zprofile"
    state: absent

- name: Delete zsh from config folder
  file:
    path: "/home/{{ user }}/.config/zsh"
    state: absent

- name: Delete .Xresources from home folder
  file:
    path: "/home/{{ user }}/.Xresources"
    state: absent
  when: ansible_distribution == 'Fedora'

- name: Change default user shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Link .profile into home folder
  file:
    src: "{{ playbook_dir }}/.profile"
    dest: "/home/{{ user }}/.profile"
    state: link

- name: Link .zprofile into home folder
  file:
    src: "{{ playbook_dir }}/.zprofile"
    dest: "/home/{{ user }}/.zprofile"
    state: link

- name: Link alacritty config
  file:
    src: "{{ playbook_dir }}/config/alacritty"
    dest: "/home/{{ user }}/.config/alacritty"
    state: link

- name: Link bspwm config
  file:
    src: "{{ playbook_dir }}/config/bspwm"
    dest: "/home/{{ user }}/.config/bspwm"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Link dunst config
  file:
    src: "{{ playbook_dir }}/config/dunst"
    dest: "/home/{{ user }}/.config/dunst"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Link nvim config
  file:
    src: "{{ playbook_dir }}/config/nvim"
    dest: "/home/{{ user }}/.config/nvim"
    state: link

- name: Link picom config
  file:
    src: "{{ playbook_dir }}/config/picom.conf"
    dest: "/home/{{ user }}/.config/picom.conf"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Link starship config
  file:
    src: "{{ playbook_dir }}/config/starship.toml"
    dest: "/home/{{ user }}/.config/starship.toml"
    state: link

- name: Link sxhkd config
  file:
    src: "{{ playbook_dir }}/config/sxhkd"
    dest: "/home/{{ user }}/.config/sxhkd"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Link X11 config
  file:
    src: "{{ playbook_dir }}/config/X11"
    dest: "/home/{{ user }}/.config/X11"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Link zsh config
  file:
    src: "{{ playbook_dir }}/config/zsh"
    dest: "/home/{{ user }}/.config/zsh"
    state: link

- name: Link scripts into bin
  file:
    src: "{{ playbook_dir }}/scripts"
    dest: "/home/{{ user }}/.local/bin/scripts"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Copy mouse settings into system folder
  copy:
    src: "{{ playbook_dir }}/.to-download/40-libinput.conf"
    dest: "/etc/X11/xorg.conf.d/40-libinput.conf"
  when: ansible_distribution == 'Fedora'

- name: Edit rofi config to have hack nerd font
  lineinfile:
    path: /home/{{user}}/.config/rofi/config.rasi 
    search_string: "font: \"Jetbrains Mono 12\";"
    line: "font: \"Hack Nerd Font Mono 12\";"
  when: ansible_distribution == 'Fedora'

- name: Enable and start libvirtd service
  systemd_service:
    name: libvirtd
    enabled: true
    state: started
  when: ansible_distribution == 'Fedora'
