- name: Update packages (Fedora)
  ansible_become_pass: "{{ password }}"
  become: yes
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Update packages (ParrotOS)
  ansible_become_pass: "{{ password }}"
  become: yes
  apt:
    name: "*"
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Install packages (Fedora)
  ansible_become_pass: "{{ password }}"
  become: yes
  dnf:
    name: "{{ packages_fedora }}"
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Install packages (ParrotOS)
  ansible_become_pass: "{{ password }}"
  become: yes
  apt:
    name: "{{ packages_parrot }}"
    state: latest
  when: ansible_distribution == 'Parrot'

- name: Download installer script for starship
  get_url: 
    url: https://starship.rs/install.sh
    dest: "/home/{{ user }}/Downloads/starship_install.sh"
    mode: '0755'

- name : Run installer script for starship
  command: "/home/{{ user }}/Downloads/starship_install.sh"

- name: Clone zsh autosuggestions plugin into .config
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ user }}/.config/zsh/zsh-autosuggestions"

- name: Clone zsh syntax highlighting plugins into .config
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ user }}/.config/zsh/zsh-syntax-highlighting"

- name: Copy Dracula into .themes
  file:
    src: "{{ playbook_dir }}/.to-download/Dracula"
    dest: "/home/{{ user }}/.themes/Dracula"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Clone qt5 Dracula theme
  git:
    repo: https://github.com/dracula/qt5.git
    dest: "/home/{{ user }}/Downloads/qt5_dracula"
  when: ansible_distribution == 'Fedora'

- name: Symlink Dracula theme to qt5 config
  file:
    src: "/home/{{ user }}/Downloads/qt5_dracula/Dracula.conf"
    dest: "/home/{{ user }}/.config/qt5ct/colors/Dracula.conf"
    state: link
  when: ansible_distribution == 'Fedora'

- name: Create a fonts directory
  file:
    path: /home/{{user}}/.local/share/fonts
    state: directory

- name: Get and unpack Hack Font
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.0/Hack.zip 
    dest: "/home/{{user}}/.local/share/fonts"
