- name: Update packages
  become_user: root
  dnf:
    name: "*"
    state: latest

- name: Install packages
  become_user: root
  dnf:
    name: "{{ packages }}"
    state: latest

- name: Download installer script for starship
  get_url: 
    url: https://starship.rs/install.sh
    dest: "/home/{{ user }}/Downloads/starship_install.sh"
    mode: '0755'

- name : Run installer script for starship
  command: "/home/{{ user }}/Downloads/starship_install.sh"

- name: Clone zsh autosuggestions plugin into .config
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ user }}/.config/zsh/zsh-autosuggestions"

- name: Clone zsh syntax highlighting plugins into .config
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ user }}/.config/zsh/zsh-syntax-highlighting"

- name: Copy Dracula into .themes
  file:
    src: "{{ playbook_dir }}/.to-download/Dracula"
    dest: "/home/{{ user }}/.themes/Dracula"
    state: link


- name: Clone qt5 Dracula theme
  git:
    repo: https://github.com/dracula/qt5.git
    dest: "/home/{{ user }}/Downloads/qt5_dracula"

- name: Symlink Dracula theme to qt5 config
  file:
    src: "/home/{{ user }}/Downloads/qt5_dracula/Dracula.conf"
    dest: "/home/{{ user }}/.config/qt5ct/colors/Dracula.conf"
    state: link
