- name: Update packages
  become_user: root
  dnf:
    name: "*"
    state: latest

- name: Install packages
  become_user: root
  dnf:
    name: "{{ packages }}"
    state: latest

- name: Download installer script for starship
  get_url: 
    url: https://starship.rs/install.sh
    dest: /home/{{ user }}/Downloads/starship_install.sh
    mode: '0755'

- name : Run installer script for starship
  command: /home/{{ user }}/Downloads/starship_install.sh

- name: Clone zsh autosuggestions plugin into .config
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ user }}/.config/zsh/zsh-autosuggestions

- name: Clone zsh syntax highlighting plugins into .config
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ user }}/.config/zsh/zsh-syntax-highlighting
