user: INSERT USER HERE
packages_fedora:
  - alacritty
  - alsa-utils
  - android-tools
  - arandr
  - blueman
  - brightnessctl
  - bspwm
  - discord
  - rofi
  - podman
  - dunst
  - exa
  - feh
  - librewolf
  - fuse
  - fzf
  - gnome-keyring
  - htop
  - i3lock
  - lxappearance
  - maim
  - mpv
  - mullvad-vpn
  - mupdf
  - neofetch
  - neovim
  - tmux
  - network-manager-applet
  - pandoc
  - picom
  - piper
  - playerctl
  - python
  - qt5ct
  - remmina
  - sxhkd
  - transmission-cli
  - wireguard-tools
  - xautolock
  - xclip
  - breeze-cursor-theme
  - xdotool
  - zsh
  - solaar
  - prettyping
  - bat
  - "@virtualization"
  - syncthing
  - stow

packages_parrot:
  - alacritty
  - podman
  - exa
  - fzf
  - htop
  - neofetch
  - neovim
  - tmux
  - remmina
  - wireguard-tools
  - prettyping
  - bat
  - zsh
  - stow
