#!/bin/sh
#
# ~/.config/X11/xinitrc
#
# Executed by startx (run your window manager from here)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

DEFAULT_SESSION=gnome-session

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xsetroot -cursor_name left_ptr &

export DESKTOP_SESSION="bspwm"

lock.sh
feh --bg-fill --no-fehbg ~/Media/Wallpapers/lain.png 
~/.config/dunst/launch.sh
blueman-applet
killall -q gnome-keyring-daemon
while pgrep gnome-keyring-daemon; do sleep 0.01s; done
gnome-keyring-daemon -d
killall -q picom
while pgrep picom; do sleep 0.01s; done
picom -b
killall -q sxhkd
while pgrep sxhkd; do sleep 0.01s; done
sxhkd &
exec bspwm
