version: '3.8'
services:
  netbird:
    image: netbirdio/netbird:latest
    hostname: homelab
    network_mode: host
    restart: unless-stopped
    cap_add: 
      - NET_ADMIN 
      - SYS_ADMIN 
      - SYS_RESOURCE  
    volumes: 
      - /var/netbird:/etc/netbird 
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
  caddy:
    build: ./data/caddy/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/caddy/data:/data
      - /var/caddy/config:/config
  restic:
    image: mazzolino/restic
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RUN_ON_STARTUP: "true"
      RESTIC_COMPRESSION: auto
      RESTIC_BACKUP_SOURCES: /backup
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --verbose
      BACKUP_CRON: "0 30 3 * * *"
      TZ: "America/Los_Angeles"
    volumes: 
      - /var/vaultwarden:/backup/vaultw
      - /var/syncthing:/backup/syncthing
      - /var/portainer:/backup/portainer
      - /var/pihole:/backup/pihole
      - /var/pihole-dnsmasq:/backup/pihole-dnsmasq
networks:
  default:
    external: true
    name: proxy

