version: '3.8'
name: container-mgr
services:
  portainer:
    image: portainer/portainer-ce:2.21.3
    restart: unless-stopped 
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /var/portainer:/data 
networks:
  default:
    external: true
    name: proxy
