add_newline = false

format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $character"""

[directory]
style = "bold cyan"

[username]
disabled = false
show_always = true
style_user = "bold #b18ef9"
