#! /bin/sh

#### WORKSPACES ####
mons.sh

#### LOCKING ####
lock.sh

background=$(xrdb -query | grep "bg" | cut -f2 | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | head -n 1)
color9=$(xrdb -query | grep "color9" | cut -f2 | head -n 1)
color10=$(xrdb -query | grep "color10" | cut -f2 | head -n 1)
color11=$(xrdb -query | grep "color11" | cut -f2 | head -n 1)
color12=$(xrdb -query | grep "color12" | cut -f2 | head -n 1)
color13=$(xrdb -query | grep "color13" | cut -f2 | head -n 1)
color14=$(xrdb -query | grep "color14" | cut -f2 | head -n 1)
color15=$(xrdb -query | grep "color15" | cut -f2 | head -n 1)

#### BSPWM configuration ####
bspc config border_width                  3
bspc config window_gap                    10
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                button1
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config top_monocle_padding           0
bspc config right_monocle_padding         0
bspc config bottom_monocle_padding        0
bspc config left_monocle_padding          0
bspc config focus_follows_pointer         false
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

#### BSPWM coloring ####
bspc config normal_border_color	        "#666666"
bspc config focused_border_color	    "$color4"
bspc config active_border_color         "$color14"
bspc config presel_feedback_color       "$color8"

#### BSPWM rules ####
bspc rule -a dmenu state floating

#### AUTOSTART ####
# Commented these out as xinitrc does all this already
# feh --bg-scale --no-fehbg ~/Pictures/pleasebullymekohai.jpeg
# feh --bg-scale --no-fehbg ~/Pictures/wallpaperflare.com_wallpaper.jpg
# feh --bg-scale --no-fehbg ~/Pictures/shinobu_kocho.png
# feh --bg-scale --no-fehbg ~/Pictures/kocho.jpeg
# feh --bg-scale --no-fehbg ~/Pictures/mamimi_never_knows_best.png
# feh --bg-scale --no-fehbg ~/Pictures/mamimi_and_naota.png
# feh --bg-scale --no-fehbg ~/Pictures/download.jpeg
# feh --bg-scale --no-fehbg ~/Pictures/mamimi_lofi_vibe.jpg
# feh --bg-scale --no-fehbg ~/Pictures/htt_gang.jpg
# feh --bg-scale --no-fehbg ~/Pictures/zero_two_pluto_projector.jpg
# feh --bg-scale --no-fehbg ~/Pictures/mamimi_kodak.jpg
# killall -q gnome-keyring-daemon
# while pgrep gnome-keyring; do sleep 0.01s; done
# gnome-keyring-daemon -d
# killall -q picom
# while pgrep picom; do sleep 0.01s; done
# picom -b
# killall -q sxhkd
# while pgrep sxhkd; do sleep 0.01s; done
# sxhkd -c "$XDG_CONFIG_HOME/sxhkd/sxhkdrc.bspwm" &
# ~/.config/dunst/launch.sh
