#!/bin/sh
#
# ~/.config/X11/xinitrc
#
# Executed by startx (run your window manager from here)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

DEFAULT_SESSION=gnome-session

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xsetroot -cursor_name left_ptr &

export DESKTOP_SESSION="dwm"

# mons.sh
lock.sh
# feh --bg-scale --no-fehbg ~/Pictures/mamimi_lofi_vibe.jpg
# feh --bg-scale --no-fehbg ~/Pictures/htt_gang.jpg
# feh --bg-scale --no-fehbg ~/Pictures/zero_two_pluto_projector.jpg
# feh --bg-scale --no-fehbg ~/Pictures/mamimi_kodak.jpg
# feh --bg-scale --no-fehbg ~/Pictures/rascal_dreams_of_bunny_girl_mai_san.jpg
# feh --bg-scale --no-fehbg ~/Pictures/mai_san_does_not_dream_of_rascal.jpg
# feh --bg-scale --no-fehbg ~/Pictures/bust_a_yui.png
# feh --bg-scale --no-fehbg ~/Pictures/sakura.jpg
feh --bg-scale --no-fehbg ~/Pictures/bna.png
~/.config/dunst/launch.sh
killall -q gnome-keyring-daemon
while pgrep gnome-keyring-daemon; do sleep 0.01s; done
gnome-keyring-daemon -d
killall -q picom
while pgrep picom; do sleep 0.01s; done
picom -b
killall -q sxhkd
while pgrep sxhkd; do sleep 0.01s; done
sxhkd &
exec ssh-agent dwm
