version: '3.8'
services:
  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /var/syncthing:/var/syncthing
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      ADMIN_TOKEN: ${VAULTW_ADMIN_TOKEN}
    volumes: 
      - /var/vaultwarden:/data
  gitea:
    image: docker.io/gitea/gitea:1.22.6
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DISABLE_REGISTRATION: true
    restart: always
    volumes:
      - /var/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 222:22
networks:
  default:
    external: true
    name: proxy

